on:
  schedule:
    - cron: "30 10 * * *"
  push:
    branches:
      - primary
      - actions
  # FIXME change to only deploy on main

jobs:
  deploy-sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@v1.4.0
        with:
          branch: "primary"
          git_push_flags: "--force"
          git_remote_url: "ssh://${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_HOST }}:22/${{ secrets.DEPLOYMENT_APP }}"
          ssh_private_key: ${{ secrets.DEPLOYMENT_KEY }}
      - name: Reset sandbox
        run: ssh -t ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_HOST }} -- run ${{ secrets.DEPLOYMENT_APP }} mix reset_sandbox
