on:
  push:
    branches:
      - primary

jobs:
  deploy-sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@v1.4.0
        with:
          branch: "primary"
          git_remote_url: "ssh://${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_HOST }}:22/${{ secrets.DEPLOYMENT_APP }}"
          ssh_private_key: ${{ secrets.DEPLOYMENT_KEY }}
