on:
  schedule:
    - cron: "30 10 * * *"

jobs:
  reset-sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Reset sandbox
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: run ${{ secrets.DEPLOYMENT_APP }} mix reset_sandbox
